// Generated by ReScript, PLEASE EDIT WITH CARE


var Columns_arrayOf = {};

var Columns = {};

var Spacing_arrayOf = {};

var Spacing = {};

var Sx_arrayOf = {};

var Sx = {};

export {
  Columns_arrayOf ,
  Columns ,
  Spacing_arrayOf ,
  Spacing ,
  Sx_arrayOf ,
  Sx ,
}
/* No side effect */
