// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lab from "@mui/lab";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Timeline from "@mui/lab/Timeline";
import * as JsxRuntime from "react/jsx-runtime";
import TimelineDot from "@mui/lab/TimelineDot";
import TimelineItem from "@mui/lab/TimelineItem";
import Typography from "@mui/material/Typography";
import TimelineConnector from "@mui/lab/TimelineConnector";
import TimelineSeparator from "@mui/lab/TimelineSeparator";
import TimelineOppositeContent from "@mui/lab/TimelineOppositeContent";

function ExampleTimeline(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Timeline Examples:"
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Basic Timeline:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Timeline, {
                      id: "timeline-basic",
                      children: [
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {}),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Eat"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {}),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Code"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineSeparator, {
                                      children: Caml_option.some(JsxRuntime.jsx(TimelineDot, {}))
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Sleep"
                                    })
                              ]
                            })
                      ]
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Timeline with Colored Dots:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Timeline, {
                      id: "timeline-colors",
                      children: [
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "primary"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Primary"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "secondary"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Secondary"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "success"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Success"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineSeparator, {
                                      children: Caml_option.some(JsxRuntime.jsx(TimelineDot, {
                                                color: "error"
                                              }))
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Error"
                                    })
                              ]
                            })
                      ]
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Timeline with Outlined Dots:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Timeline, {
                      id: "timeline-outlined",
                      children: [
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "primary",
                                              variant: "outlined"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Outlined Primary"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineSeparator, {
                                      children: Caml_option.some(JsxRuntime.jsx(TimelineDot, {
                                                color: "secondary",
                                                variant: "outlined"
                                              }))
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Outlined Secondary"
                                    })
                              ]
                            })
                      ]
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Timeline with Opposite Content:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Timeline, {
                      id: "timeline-opposite",
                      children: [
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineOppositeContent, {
                                      color: "textSecondary",
                                      children: "09:30 am"
                                    }),
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "primary"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Wake up"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineOppositeContent, {
                                      color: "textSecondary",
                                      children: "10:00 am"
                                    }),
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "success"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Breakfast"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineOppositeContent, {
                                      color: "textSecondary",
                                      children: "12:00 pm"
                                    }),
                                JsxRuntime.jsx(TimelineSeparator, {
                                      children: Caml_option.some(JsxRuntime.jsx(TimelineDot, {
                                                color: "info"
                                              }))
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Lunch"
                                    })
                              ]
                            })
                      ],
                      position: "right"
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Alternating Timeline:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Timeline, {
                      id: "timeline-alternate",
                      children: [
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "primary"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Step 1"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "secondary"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Step 2"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {
                                              color: "success"
                                            }),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Step 3"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineSeparator, {
                                      children: Caml_option.some(JsxRuntime.jsx(TimelineDot, {
                                                color: "warning"
                                              }))
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Step 4"
                                    })
                              ]
                            })
                      ],
                      position: "alternate"
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Left-positioned Timeline:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Timeline, {
                      id: "timeline-left",
                      children: [
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsxs(TimelineSeparator, {
                                      children: [
                                        JsxRuntime.jsx(TimelineDot, {}),
                                        JsxRuntime.jsx(TimelineConnector, {})
                                      ]
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Left item 1"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(TimelineItem, {
                              children: [
                                JsxRuntime.jsx(TimelineSeparator, {
                                      children: Caml_option.some(JsxRuntime.jsx(TimelineDot, {}))
                                    }),
                                JsxRuntime.jsx(Lab.TimelineContent, {
                                      children: "Left item 2"
                                    })
                              ]
                            })
                      ],
                      position: "left"
                    })
              ]
            });
}

var make = ExampleTimeline;

export {
  make ,
}
/* @mui/lab Not a pure module */
