// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Lab from "@material-ui/lab";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import ExpandMore from "@material-ui/icons/ExpandMore";
import ChevronRight from "@material-ui/icons/ChevronRight";

var ExpandMoreIcon = {};

var ChevronRightIcon = {};

function ExampleTreeView(props) {
  return JsxRuntime.jsx(Core.Box, {
              clone: true,
              children: Caml_option.some(JsxRuntime.jsxs(Lab.TreeView, {
                        children: [
                          JsxRuntime.jsxs(Lab.TreeItem, {
                                children: [
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "Calendar",
                                        nodeId: "2"
                                      }),
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "Chrome",
                                        nodeId: "3"
                                      }),
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "Webstorm",
                                        nodeId: "4"
                                      })
                                ],
                                label: "Applications",
                                nodeId: "1"
                              }),
                          JsxRuntime.jsxs(Lab.TreeItem, {
                                children: [
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "OSS",
                                        nodeId: "10"
                                      }),
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        children: Caml_option.some(JsxRuntime.jsxs(Lab.TreeItem, {
                                                  children: [
                                                    JsxRuntime.jsx(Lab.TreeItem, {
                                                          label: "index.js",
                                                          nodeId: "8"
                                                        }),
                                                    JsxRuntime.jsx(Lab.TreeItem, {
                                                          label: "tree-view.js",
                                                          nodeId: "9"
                                                        })
                                                  ],
                                                  label: "src",
                                                  nodeId: "7"
                                                })),
                                        label: "Material-UI",
                                        nodeId: "6"
                                      })
                                ],
                                label: "Documents",
                                nodeId: "5"
                              })
                        ],
                        defaultCollapseIcon: Caml_option.some(JsxRuntime.jsx(ExpandMore, {})),
                        defaultExpandIcon: Caml_option.some(JsxRuntime.jsx(ChevronRight, {}))
                      })),
              flexGrow: 1,
              height: "240px",
              maxWidth: "400px"
            });
}

var make = ExampleTreeView;

export {
  ExpandMoreIcon ,
  ChevronRightIcon ,
  make ,
}
/* @material-ui/lab Not a pure module */
