// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lab from "@material-ui/lab";

function ExampleSkeleton(Props) {
  return React.createElement("div", undefined, React.createElement(Lab.Skeleton, {
                  variant: "text"
                }), React.createElement(Lab.Skeleton, {
                  height: 40,
                  variant: "circle",
                  width: 40
                }), React.createElement(Lab.Skeleton, {
                  height: 118,
                  variant: "rect",
                  width: 210
                }));
}

var make = ExampleSkeleton;

export {
  make ,
}
/* react Not a pure module */
