// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Grid$Mui from "rescript-material-ui/src/Grid.bs.js";
import * as ExampleAlert from "./ExampleAlert.bs.js";
import * as ExampleRating from "./ExampleRating.bs.js";
import * as ExampleSkeleton from "./ExampleSkeleton.bs.js";
import * as ExampleTreeView from "./ExampleTreeView.bs.js";
import * as Core from "@material-ui/core";
import * as ExamplePagination from "./ExamplePagination.bs.js";
import * as ExampleAutocomplete from "./ExampleAutocomplete.bs.js";
import * as ExampleToggleButton from "./ExampleToggleButton.bs.js";

function ExamplesLab(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Core.Grid, {
                  children: React.createElement(Core.Grid, {
                        children: React.createElement(Core.Typography, {
                              children: "ReScript Material-UI Lab Examples",
                              variant: "h4"
                            }),
                        item: true,
                        md: Grid$Mui.Md[12]
                      }),
                  container: true
                }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "Alert",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExampleAlert.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "Autocomplete",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExampleAutocomplete.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "Pagination",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExamplePagination.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "Rating",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExampleRating.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "Skeleton",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExampleSkeleton.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "ToggleButton",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExampleToggleButton.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Divider, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.Grid, {
                  alignItems: "center",
                  children: null,
                  container: true
                }, React.createElement(Core.Grid, {
                      children: React.createElement(Core.Typography, {
                            children: "TreeView",
                            variant: "h5"
                          }),
                      item: true,
                      md: Grid$Mui.Md[6]
                    }), React.createElement(Core.Grid, {
                      children: React.createElement(ExampleTreeView.make, {}),
                      item: true,
                      md: Grid$Mui.Md[6]
                    })), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined));
}

var make = ExamplesLab;

export {
  make ,
  
}
/* react Not a pure module */
