// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import TreeItem from "@mui/lab/TreeItem";
import TreeView from "@mui/lab/TreeView";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import ExpandMore from "@mui/icons-material/ExpandMore";
import ChevronRight from "@mui/icons-material/ChevronRight";

var ExpandMoreIcon = {};

var ChevronRightIcon = {};

function ExampleTreeView(props) {
  return JsxRuntime.jsx(Box, {
              flexGrow: 1,
              height: "240px",
              maxWidth: "400px",
              children: Caml_option.some(JsxRuntime.jsxs(TreeView, {
                        children: [
                          JsxRuntime.jsxs(TreeItem, {
                                nodeId: "1",
                                children: [
                                  JsxRuntime.jsx(TreeItem, {
                                        nodeId: "2",
                                        label: "Calendar"
                                      }),
                                  JsxRuntime.jsx(TreeItem, {
                                        nodeId: "3",
                                        label: "Chrome"
                                      }),
                                  JsxRuntime.jsx(TreeItem, {
                                        nodeId: "4",
                                        label: "Webstorm"
                                      })
                                ],
                                label: "Applications"
                              }),
                          JsxRuntime.jsxs(TreeItem, {
                                nodeId: "5",
                                children: [
                                  JsxRuntime.jsx(TreeItem, {
                                        nodeId: "10",
                                        label: "OSS"
                                      }),
                                  JsxRuntime.jsx(TreeItem, {
                                        nodeId: "6",
                                        children: Caml_option.some(JsxRuntime.jsxs(TreeItem, {
                                                  nodeId: "7",
                                                  children: [
                                                    JsxRuntime.jsx(TreeItem, {
                                                          nodeId: "8",
                                                          label: "index.js"
                                                        }),
                                                    JsxRuntime.jsx(TreeItem, {
                                                          nodeId: "9",
                                                          label: "tree-view.js"
                                                        })
                                                  ],
                                                  label: "src"
                                                })),
                                        label: "Material-UI"
                                      })
                                ],
                                label: "Documents"
                              })
                        ],
                        defaultCollapseIcon: Caml_option.some(JsxRuntime.jsx(ExpandMore, {})),
                        defaultExpandIcon: Caml_option.some(JsxRuntime.jsx(ChevronRight, {}))
                      }))
            });
}

var make = ExampleTreeView;

export {
  ExpandMoreIcon ,
  ChevronRightIcon ,
  make ,
}
/* @mui/lab/TreeItem Not a pure module */
