// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lab from "@mui/lab";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";
import ExpandMore from "@mui/icons-material/ExpandMore";
import ChevronRight from "@mui/icons-material/ChevronRight";

var ExpandMoreIcon = {};

var ChevronRightIcon = {};

function ExampleTreeView(props) {
  return JsxRuntime.jsx((function (prim) {
                return Material.Box(prim);
              }), {
              flexGrow: 1,
              height: "240px",
              maxWidth: "400px",
              children: Caml_option.some(JsxRuntime.jsxs(Lab.TreeView, {
                        children: [
                          JsxRuntime.jsxs(Lab.TreeItem, {
                                children: [
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "Calendar",
                                        nodeId: "2"
                                      }),
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "Chrome",
                                        nodeId: "3"
                                      }),
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "Webstorm",
                                        nodeId: "4"
                                      })
                                ],
                                label: "Applications",
                                nodeId: "1"
                              }),
                          JsxRuntime.jsxs(Lab.TreeItem, {
                                children: [
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        label: "OSS",
                                        nodeId: "10"
                                      }),
                                  JsxRuntime.jsx(Lab.TreeItem, {
                                        children: Caml_option.some(JsxRuntime.jsxs(Lab.TreeItem, {
                                                  children: [
                                                    JsxRuntime.jsx(Lab.TreeItem, {
                                                          label: "index.js",
                                                          nodeId: "8"
                                                        }),
                                                    JsxRuntime.jsx(Lab.TreeItem, {
                                                          label: "tree-view.js",
                                                          nodeId: "9"
                                                        })
                                                  ],
                                                  label: "src",
                                                  nodeId: "7"
                                                })),
                                        label: "Material-UI",
                                        nodeId: "6"
                                      })
                                ],
                                label: "Documents",
                                nodeId: "5"
                              })
                        ],
                        defaultCollapseIcon: Caml_option.some(JsxRuntime.jsx(ExpandMore, {})),
                        defaultExpandIcon: Caml_option.some(JsxRuntime.jsx(ChevronRight, {}))
                      }))
            });
}

var make = ExampleTreeView;

export {
  ExpandMoreIcon ,
  ChevronRightIcon ,
  make ,
}
/* @mui/lab Not a pure module */
