// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ExampleAlert from "../examples/ExampleAlert.bs.js";
import * as ExampleRating from "../examples/ExampleRating.bs.js";
import * as ExampleSkeleton from "../examples/ExampleSkeleton.bs.js";
import * as ExamplePagination from "../examples/ExamplePagination.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import Grid from "@mui/material/Grid";
import * as ExampleAutocomplete from "../examples/ExampleAutocomplete.bs.js";
import * as ExampleToggleButton from "./ExampleToggleButton.bs.js";
import Divider from "@mui/material/Divider";
import Typography from "@mui/material/Typography";

function ExamplesLab(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(Grid, {
                                children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                          variant: "h4",
                                          children: "ReScript-MUI Lab Examples"
                                        })),
                                item: true,
                                md: 12
                              })),
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs(Grid, {
                      alignItems: "center",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                        variant: "h5",
                                        children: "Alert"
                                      })),
                              item: true,
                              md: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleAlert.make, {})),
                              item: true,
                              md: 6
                            })
                      ],
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs(Grid, {
                      alignItems: "center",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                        variant: "h5",
                                        children: "Autocomplete"
                                      })),
                              item: true,
                              md: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleAutocomplete.make, {})),
                              item: true,
                              md: 6
                            })
                      ],
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs(Grid, {
                      alignItems: "center",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                        variant: "h5",
                                        children: "Pagination"
                                      })),
                              item: true,
                              md: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExamplePagination.make, {})),
                              item: true,
                              md: 6
                            })
                      ],
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs(Grid, {
                      alignItems: "center",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                        variant: "h5",
                                        children: "Rating"
                                      })),
                              item: true,
                              md: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleRating.make, {})),
                              item: true,
                              md: 6
                            })
                      ],
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs(Grid, {
                      alignItems: "center",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                        variant: "h5",
                                        children: "Skeleton"
                                      })),
                              item: true,
                              md: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleSkeleton.make, {})),
                              item: true,
                              md: 6
                            })
                      ],
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs(Grid, {
                      alignItems: "center",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                        variant: "h5",
                                        children: "ToggleButton"
                                      })),
                              item: true,
                              md: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleToggleButton.make, {})),
                              item: true,
                              md: 6
                            })
                      ],
                      container: true
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Divider, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {})
              ]
            });
}

var make = ExamplesLab;

export {
  make ,
}
/* ExampleAlert Not a pure module */
