// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Masonry from "@mui/lab/Masonry";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Card from "@mui/material/Card";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import CardContent from "@mui/material/CardContent";

var itemHeights = [
  150,
  100,
  200,
  120,
  180,
  90,
  160,
  110,
  140,
  130,
  170,
  100
];

function ExampleMasonry(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Masonry Examples:"
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "body2",
                      children: "Masonry lays out contents of varying dimensions as blocks packed in a container.",
                      sx: {
                        marginBottom: "16px"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Basic Masonry (3 columns):",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsx(Box, {
                      children: Caml_option.some(JsxRuntime.jsx(Masonry, {
                                id: "masonry-basic",
                                children: Belt_Array.mapWithIndex(itemHeights, (function (i, height) {
                                        var match = i % 4;
                                        var tmp;
                                        switch (match) {
                                          case 0 :
                                              tmp = "primary.light";
                                              break;
                                          case 1 :
                                              tmp = "secondary.light";
                                              break;
                                          case 2 :
                                              tmp = "success.light";
                                              break;
                                          default:
                                            tmp = "warning.light";
                                        }
                                        return JsxRuntime.jsx(Paper, {
                                                    sx: {
                                                      display: "flex",
                                                      alignItems: "center",
                                                      justifyContent: "center",
                                                      bgcolor: tmp,
                                                      height: String(height) + "px"
                                                    },
                                                    children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                                              children: Caml_option.some(String(i + 1 | 0) + " (" + String(height) + "px)")
                                                            }))
                                                  }, String(i));
                                      })),
                                columns: 3,
                                spacing: 2
                              })),
                      sx: {
                        minHeight: "400px",
                        width: "100%"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Masonry (4 columns, spacing 1):",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "24px"
                      }
                    }),
                JsxRuntime.jsx(Box, {
                      children: Caml_option.some(JsxRuntime.jsx(Masonry, {
                                id: "masonry-4col",
                                children: Belt_Array.mapWithIndex(Belt_Array.slice(itemHeights, 0, 8), (function (i, height) {
                                        return JsxRuntime.jsx(Paper, {
                                                    elevation: 3,
                                                    sx: {
                                                      display: "flex",
                                                      alignItems: "center",
                                                      justifyContent: "center",
                                                      height: String(height) + "px"
                                                    },
                                                    children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                                              variant: "h6",
                                                              children: Caml_option.some(String(i + 1 | 0))
                                                            }))
                                                  }, String(i));
                                      })),
                                columns: 4,
                                spacing: 1
                              })),
                      sx: {
                        minHeight: "300px",
                        width: "100%"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Masonry (2 columns, spacing 3):",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "24px"
                      }
                    }),
                JsxRuntime.jsx(Box, {
                      children: Caml_option.some(JsxRuntime.jsx(Masonry, {
                                id: "masonry-2col",
                                children: Belt_Array.mapWithIndex(Belt_Array.slice(itemHeights, 0, 6), (function (i, height) {
                                        return JsxRuntime.jsx(Card, {
                                                    sx: {
                                                      height: String(height) + "px"
                                                    },
                                                    children: Caml_option.some(JsxRuntime.jsxs(CardContent, {
                                                              children: [
                                                                JsxRuntime.jsx(Typography, {
                                                                      component: "div",
                                                                      variant: "h5",
                                                                      children: Caml_option.some("Card " + String(i + 1 | 0))
                                                                    }),
                                                                JsxRuntime.jsx(Typography, {
                                                                      color: "textSecondary",
                                                                      variant: "body2",
                                                                      children: Caml_option.some("Height: " + String(height) + "px")
                                                                    })
                                                              ]
                                                            }))
                                                  }, String(i));
                                      })),
                                columns: 2,
                                spacing: 3
                              })),
                      sx: {
                        minHeight: "300px",
                        width: "100%"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Masonry with colored items:",
                      sx: {
                        marginBottom: "8px",
                        marginTop: "24px"
                      }
                    }),
                JsxRuntime.jsx(Box, {
                      children: Caml_option.some(JsxRuntime.jsx(Masonry, {
                                id: "masonry-colors",
                                children: Belt_Array.mapWithIndex([
                                      [
                                        "#f44336",
                                        120
                                      ],
                                      [
                                        "#e91e63",
                                        180
                                      ],
                                      [
                                        "#9c27b0",
                                        100
                                      ],
                                      [
                                        "#673ab7",
                                        150
                                      ],
                                      [
                                        "#3f51b5",
                                        200
                                      ],
                                      [
                                        "#2196f3",
                                        90
                                      ],
                                      [
                                        "#03a9f4",
                                        160
                                      ],
                                      [
                                        "#00bcd4",
                                        110
                                      ],
                                      [
                                        "#009688",
                                        140
                                      ]
                                    ], (function (i, param) {
                                        return JsxRuntime.jsx(Box, {
                                                    sx: {
                                                      borderRadius: "8px",
                                                      bgcolor: param[0],
                                                      height: String(param[1]) + "px"
                                                    }
                                                  }, String(i));
                                      })),
                                columns: 3,
                                spacing: 1
                              })),
                      sx: {
                        minHeight: "300px",
                        width: "100%"
                      }
                    })
              ]
            });
}

var make = ExampleMasonry;

export {
  itemHeights ,
  make ,
}
/* @mui/lab/Masonry Not a pure module */
