// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lab from "@material-ui/lab";

function ExamplePagination(Props) {
  return React.createElement("div", undefined, React.createElement(Lab.Pagination, {
                  count: 10
                }), React.createElement(Lab.Pagination, {
                  color: "primary",
                  count: 10
                }), React.createElement(Lab.Pagination, {
                  color: "secondary",
                  count: 10
                }), React.createElement(Lab.Pagination, {
                  count: 10,
                  disabled: true
                }));
}

var make = ExamplePagination;

export {
  make ,
  
}
/* react Not a pure module */
