// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lab from "@material-ui/lab";

function ExampleAlert(Props) {
  return React.createElement("div", undefined, React.createElement(Lab.Alert, {
                  children: "This is an error alert — check it out!",
                  severity: "error"
                }), React.createElement(Lab.Alert, {
                  children: "This is a warning alert — check it out!",
                  severity: "warning"
                }), React.createElement(Lab.Alert, {
                  children: "This is an info alert — check it out!",
                  severity: "info"
                }), React.createElement(Lab.Alert, {
                  children: "This is a success alert — check it out!",
                  severity: "success"
                }));
}

var make = ExampleAlert;

export {
  make ,
  
}
/* react Not a pure module */
