// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Examples from "./examples/Examples.bs.js";
import * as ExamplesLab from "./labExamples/ExamplesLab.bs.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/core/styles";

function App(props) {
  return JsxRuntime.jsx(Styles.ThemeProvider, {
              children: JsxRuntime.jsxs(Core.Box, {
                    children: [
                      JsxRuntime.jsx(Core.CssBaseline, {}),
                      JsxRuntime.jsx(Examples.make, {}),
                      JsxRuntime.jsx(ExamplesLab.make, {})
                    ],
                    height: "100%",
                    margin: "30px auto",
                    maxWidth: "970px",
                    width: "100%"
                  }),
              theme: Styles.createTheme({})
            });
}

var make = App;

export {
  make ,
}
/* Examples Not a pure module */
