// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Examples from "./examples/Examples.bs.js";
import * as ExamplesLab from "./labExamples/ExamplesLab.bs.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

function App(props) {
  return JsxRuntime.jsx(Styles.ThemeProvider, {
              children: JsxRuntime.jsxs(Box, {
                    height: "100%",
                    maxWidth: "970px",
                    width: "100%",
                    margin: "30px auto",
                    children: [
                      JsxRuntime.jsx(CssBaseline, {}),
                      JsxRuntime.jsx(Examples.make, {}),
                      JsxRuntime.jsx(ExamplesLab.make, {})
                    ]
                  }),
              theme: Styles.createTheme({})
            });
}

var make = App;

export {
  make ,
}
/* Examples Not a pure module */
