// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var domElement = document.querySelector("#app");

if (!(domElement == null)) {
  ReactDom.render(React.createElement(App.make, {}), domElement);
}

export {
  
}
/* domElement Not a pure module */
