// Generated by ReScript, PLEASE EDIT WITH CARE


var Sx_arrayOf = {};

var Sx = {};

var TransitionDuration_shape = {};

var TransitionDuration = {};

export {
  Sx_arrayOf ,
  Sx ,
  TransitionDuration_shape ,
  TransitionDuration ,
}
/* No side effect */
