// Generated by ReScript, PLEASE EDIT WITH CARE


var Component = {};

var Sx_arrayOf = {};

var Sx = {};

var Variant = {};

export {
  Component ,
  Sx_arrayOf ,
  Sx ,
  Variant ,
}
/* No side effect */
