// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Animation = {
  pulse: "pulse",
  wave: "wave",
  $$false: false
};

var Height = {};

var Sx_arrayOf = {};

var Sx = {};

var Variant = {};

var Width = {};

export {
  $$Animation ,
  Height ,
  Sx_arrayOf ,
  Sx ,
  Variant ,
  Width ,
}
/* No side effect */
