// Generated by ReScript, PLEASE EDIT WITH CARE


var AnchorOrigin = {};

var $$Event = {};

var Sx_arrayOf = {};

var Sx = {};

var TransitionDuration_shape = {};

var TransitionDuration = {};

export {
  AnchorOrigin ,
  $$Event ,
  Sx_arrayOf ,
  Sx ,
  TransitionDuration_shape ,
  TransitionDuration ,
}
/* No side effect */
