// Generated by ReScript, PLEASE EDIT WITH CARE


var Sx_arrayOf = {};

var Sx = {};

var Component = {};

var BackdropProps = {};

var ModalProps = {};

var PaperProps = {};

var TransitionDuration_shape = {};

var TransitionDuration = {};

export {
  Sx_arrayOf ,
  Sx ,
  Component ,
  BackdropProps ,
  ModalProps ,
  PaperProps ,
  TransitionDuration_shape ,
  TransitionDuration ,
}
/* No side effect */
