// Generated by ReScript, PLEASE EDIT WITH CARE


var Size = {};

var SortDirection = {
  asc: "asc",
  desc: "desc",
  $$false: false
};

var Variant = {};

var $$Event = {};

var Sx_arrayOf = {};

var Sx = {};

export {
  Size ,
  SortDirection ,
  Variant ,
  $$Event ,
  Sx_arrayOf ,
  Sx ,
}
/* No side effect */
