// Generated by ReScript, PLEASE EDIT WITH CARE


var IndicatorColor = {};

var ScrollButtons = {
  auto: "auto",
  $$false: false,
  $$true: true
};

var Sx_arrayOf = {};

var Sx = {};

export {
  IndicatorColor ,
  ScrollButtons ,
  Sx_arrayOf ,
  Sx ,
}
/* No side effect */
