// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "react-dom/client";
import * as Core from "@material-ui/core";
import * as NewImplementation from "./NewImplementation.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as NewImplementationPpx from "./NewImplementationPpx.bs.js";
import * as NewImplementationTheme from "./NewImplementationTheme.bs.js";
import * as NewImplementationThemePpx from "./NewImplementationThemePpx.bs.js";

function Index$App(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(NewImplementation.make, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(NewImplementationTheme.make, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("center", {
                      children: JsxRuntime.jsx(Core.Typography, {
                            children: "PPX Result",
                            variant: "h4"
                          })
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(NewImplementationPpx.make, {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(NewImplementationThemePpx.make, {})
              ]
            });
}

var App = {
  make: Index$App
};

var domElement = document.querySelector("#app");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(Index$App, {}));
}

export {
  App ,
}
/* domElement Not a pure module */
