// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import IconButton from "@mui/material/IconButton";
import Typography from "@mui/material/Typography";

function ExampleIconButton(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Icon Button Examples:"
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(IconButton, {
                              "aria-label": "primary",
                              id: "icon-button-primary",
                              children: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: "A"
                                      })),
                              color: "primary"
                            }),
                        JsxRuntime.jsx(IconButton, {
                              "aria-label": "secondary",
                              id: "icon-button-secondary",
                              children: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: "B"
                                      })),
                              color: "secondary"
                            }),
                        JsxRuntime.jsx(IconButton, {
                              "aria-label": "success",
                              id: "icon-button-success",
                              children: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: "C"
                                      })),
                              color: "success"
                            }),
                        JsxRuntime.jsx(IconButton, {
                              "aria-label": "error",
                              id: "icon-button-disabled",
                              children: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: "D"
                                      })),
                              color: "error",
                              disabled: true
                            })
                      ]
                    })
              ]
            });
}

var make = ExampleIconButton;

export {
  make ,
}
/* @mui/material/Box Not a pure module */
