// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";

function ExampleRadioGroup(props) {
  var match = React.useState(function () {
        return "Yes";
      });
  var setState = match[1];
  return JsxRuntime.jsxs(Core.RadioGroup, {
              children: [
                JsxRuntime.jsx(Core.FormControlLabel, {
                      control: JsxRuntime.jsx(Core.Radio, {}),
                      label: "Yes",
                      value: "Yes"
                    }),
                JsxRuntime.jsx(Core.FormControlLabel, {
                      control: JsxRuntime.jsx(Core.Radio, {}),
                      label: "No",
                      value: "No"
                    }),
                JsxRuntime.jsx(Core.FormControlLabel, {
                      control: JsxRuntime.jsx(Core.Radio, {}),
                      label: "Maybe",
                      value: "Maybe"
                    })
              ],
              name: "answer",
              onChange: (function (e) {
                  var value = e.target.value;
                  Curry._1(setState, (function (param) {
                          return value;
                        }));
                }),
              value: Caml_option.some(match[0])
            });
}

var make = ExampleRadioGroup;

export {
  make ,
}
/* react Not a pure module */
