// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactDOMStyle from "@rescript/react/src/ReactDOMStyle.bs.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Radio from "@mui/material/Radio";
import Select from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import FormLabel from "@mui/material/FormLabel";
import InputLabel from "@mui/material/InputLabel";
import RadioGroup from "@mui/material/RadioGroup";
import Typography from "@mui/material/Typography";
import FormControl from "@mui/material/FormControl";
import FormControlLabel from "@mui/material/FormControlLabel";

function answerToString(v) {
  switch (v) {
    case "Yes" :
        return "yes";
    case "No" :
        return "no";
    case "Maybe" :
        return "maybe";
    
  }
}

function answerFromString(s) {
  switch (s) {
    case "no" :
        return "No";
    case "yes" :
        return "Yes";
    default:
      return "Maybe";
  }
}

var options = [
  [
    "Yes",
    "Yes"
  ],
  [
    "No",
    "No"
  ],
  [
    "Maybe",
    "Maybe"
  ]
];

function sxWithQueries(base, f) {
  return [
          base,
          (function (theme) {
              return f(theme);
            })
        ];
}

function ExampleContainerQueries$RadioToSelect(props) {
  var match = React.useState(function () {
        return "Yes";
      });
  var setValue = match[1];
  var value = match[0];
  var radioSx = sxWithQueries({
        display: "none"
      }, (function (theme) {
          return Js_dict.fromArray([[
                        theme.containerQueries.up("sm"),
                        {
                          display: "block"
                        }
                      ]]);
        }));
  var selectSx = sxWithQueries({
        display: "block"
      }, (function (theme) {
          return Js_dict.fromArray([[
                        theme.containerQueries.up("sm"),
                        {
                          display: "none"
                        }
                      ]]);
        }));
  return JsxRuntime.jsxs(Box, {
              style: ReactDOMStyle.unsafeAddProp({
                    maxWidth: "100%",
                    minWidth: "180px",
                    width: "100%",
                    resize: "horizontal"
                  }, "containerType", "inline-size"),
              children: [
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(FormLabel, {
                              children: "Pick one (radio)"
                            }),
                        JsxRuntime.jsx(RadioGroup, {
                              children: Caml_option.some(Belt_Array.map(options, (function (param) {
                                          var v = param[0];
                                          return JsxRuntime.jsx(FormControlLabel, {
                                                      control: JsxRuntime.jsx(Radio, {}),
                                                      label: param[1],
                                                      value: answerToString(v)
                                                    }, answerToString(v));
                                        }))),
                              onChange: (function (e, param) {
                                  var v = e.target.value;
                                  setValue(function (param) {
                                        return answerFromString(v);
                                      });
                                }),
                              value: answerToString(value)
                            })
                      ],
                      sx: Caml_option.some(radioSx)
                    }),
                JsxRuntime.jsx(Box, {
                      children: Caml_option.some(JsxRuntime.jsxs(FormControl, {
                                children: [
                                  JsxRuntime.jsx(InputLabel, {
                                        children: "Pick one"
                                      }),
                                  JsxRuntime.jsx(Select, {
                                        value: answerToString(value),
                                        children: Caml_option.some(Belt_Array.map(options, (function (param) {
                                                    var v = param[0];
                                                    return JsxRuntime.jsx(MenuItem, {
                                                                children: Caml_option.some(param[1]),
                                                                value: answerToString(v)
                                                              }, answerToString(v));
                                                  }))),
                                        label: "Pick one",
                                        onChange: (function (e, param) {
                                            var v = e.target.value;
                                            setValue(function (param) {
                                                  return answerFromString(v);
                                                });
                                          })
                                      })
                                ],
                                fullWidth: true,
                                size: "small"
                              })),
                      sx: Caml_option.some(selectSx)
                    })
              ],
              sx: {
                border: "1px solid",
                borderColor: "divider",
                borderRadius: 1,
                padding: 2,
                overflow: "hidden"
              }
            });
}

var RadioToSelect = {
  make: ExampleContainerQueries$RadioToSelect
};

function ExampleContainerQueries$NamedContainer(props) {
  var cardSx = sxWithQueries({
        display: "flex",
        flexDirection: "column",
        gap: 1,
        padding: 2
      }, (function (theme) {
          var card = theme.containerQueries("card");
          return Js_dict.fromArray([[
                        card.up("sm"),
                        {
                          alignItems: "center",
                          flexDirection: "row",
                          gap: 3
                        }
                      ]]);
        }));
  return JsxRuntime.jsx(Box, {
              style: ReactDOMStyle.unsafeAddProp(ReactDOMStyle.unsafeAddProp({
                        maxWidth: "100%",
                        minWidth: "180px",
                        width: "100%",
                        resize: "horizontal"
                      }, "containerType", "inline-size"), "containerName", "card"),
              children: Caml_option.some(JsxRuntime.jsxs(Box, {
                        children: [
                          JsxRuntime.jsx(Box, {
                                sx: {
                                  borderRadius: "50%",
                                  flexShrink: 0,
                                  bgcolor: "primary.main",
                                  height: "48px",
                                  width: "48px"
                                }
                              }),
                          JsxRuntime.jsxs(Box, {
                                children: [
                                  JsxRuntime.jsx(Typography, {
                                        variant: "subtitle1",
                                        children: "Named container: \"card\""
                                      }),
                                  JsxRuntime.jsx(Typography, {
                                        color: "textSecondary",
                                        variant: "body2",
                                        children: "Drag to resize. Layout switches from column to row at the sm breakpoint using theme->Theme.containerQueriesNamed(\"card\").up(Sm)."
                                      })
                                ]
                              })
                        ],
                        sx: Caml_option.some(cardSx)
                      })),
              sx: {
                border: "1px solid",
                borderColor: "divider",
                borderRadius: 1,
                overflow: "hidden"
              }
            });
}

var NamedContainer = {
  make: ExampleContainerQueries$NamedContainer
};

function ExampleContainerQueries$DownAndBetween(props) {
  var sx = sxWithQueries({
        borderRadius: 1,
        bgcolor: "background.paper",
        padding: 2
      }, (function (theme) {
          var cq = theme.containerQueries;
          return Js_dict.fromArray([
                      [
                        cq.down("sm"),
                        {
                          bgcolor: "error.main",
                          color: "white"
                        }
                      ],
                      [
                        cq.between("sm", "md"),
                        {
                          bgcolor: "warning.main",
                          color: "white"
                        }
                      ],
                      [
                        cq.up("md"),
                        {
                          bgcolor: "success.main",
                          color: "white"
                        }
                      ]
                    ]);
        }));
  return JsxRuntime.jsx(Box, {
              style: ReactDOMStyle.unsafeAddProp({
                    maxWidth: "100%",
                    minWidth: "180px",
                    width: "100%",
                    resize: "horizontal"
                  }, "containerType", "inline-size"),
              children: Caml_option.some(JsxRuntime.jsx(Box, {
                        children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                  variant: "body1",
                                  children: "down(Sm) = red, between(Sm, Md) = amber, up(Md) = green"
                                })),
                        sx: Caml_option.some(sx)
                      })),
              sx: {
                border: "1px solid",
                borderColor: "divider",
                borderRadius: 1,
                overflow: "hidden"
              }
            });
}

var DownAndBetween = {
  make: ExampleContainerQueries$DownAndBetween
};

function ExampleContainerQueries(props) {
  return JsxRuntime.jsxs(Box, {
              display: "flex",
              flexDirection: "column",
              gap: 2,
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Container Queries (v6)"
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "body2",
                      children: "Drag the bottom-right corner of each box to resize and observe the layout change."
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Unnamed container: Radio \u2194 Select"
                    }),
                JsxRuntime.jsx(ExampleContainerQueries$RadioToSelect, {}),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Named container: Column \u2194 Row"
                    }),
                JsxRuntime.jsx(ExampleContainerQueries$NamedContainer, {}),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "down / between / up"
                    }),
                JsxRuntime.jsx(ExampleContainerQueries$DownAndBetween, {})
              ]
            });
}

var make = ExampleContainerQueries;

export {
  answerToString ,
  answerFromString ,
  options ,
  sxWithQueries ,
  RadioToSelect ,
  NamedContainer ,
  DownAndBetween ,
  make ,
}
/* react Not a pure module */
