// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Accordion from "@mui/material/Accordion";
import Typography from "@mui/material/Typography";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";

function ExampleAccordionSummary(props) {
  var match = React.useState(function () {
        return "";
      });
  var setExpanded = match[1];
  var expanded = match[0];
  var handleChange = function (_event, isExpanded, panel) {
    setExpanded(function (param) {
          if (isExpanded) {
            return panel;
          } else {
            return "";
          }
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "AccordionSummary Examples:"
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsxs(Accordion, {
                              children: [
                                JsxRuntime.jsx(AccordionSummary, {
                                      "aria-controls": "panel1a-content",
                                      id: "accordion-summary-1",
                                      children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                                children: "Accordion 1"
                                              })),
                                      expandIcon: Caml_option.some(JsxRuntime.jsx("span", {
                                                children: "⌄"
                                              }))
                                    }),
                                JsxRuntime.jsx(AccordionDetails, {
                                      children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                                children: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex, sit amet blandit leo lobortis eget."
                                              }))
                                    })
                              ],
                              expanded: expanded === "panel1",
                              onChange: (function (e, exp) {
                                  handleChange(e, exp, "panel1");
                                })
                            }),
                        JsxRuntime.jsxs(Accordion, {
                              children: [
                                JsxRuntime.jsx(AccordionSummary, {
                                      "aria-controls": "panel2a-content",
                                      id: "accordion-summary-2",
                                      children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                                children: "Accordion 2"
                                              })),
                                      expandIcon: Caml_option.some(JsxRuntime.jsx("span", {
                                                children: "⌄"
                                              }))
                                    }),
                                JsxRuntime.jsx(AccordionDetails, {
                                      children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                                children: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus ex, sit amet blandit leo lobortis eget."
                                              }))
                                    })
                              ],
                              expanded: expanded === "panel2",
                              onChange: (function (e, exp) {
                                  handleChange(e, exp, "panel2");
                                })
                            }),
                        JsxRuntime.jsx(Accordion, {
                              children: JsxRuntime.jsx(AccordionSummary, {
                                    "aria-controls": "panel3a-content",
                                    id: "accordion-summary-disabled",
                                    children: Caml_option.some(JsxRuntime.jsx(Typography, {
                                              children: "Disabled Accordion"
                                            })),
                                    expandIcon: Caml_option.some(JsxRuntime.jsx("span", {
                                              children: "⌄"
                                            }))
                                  }),
                              disabled: true
                            })
                      ]
                    })
              ]
            });
}

var make = ExampleAccordionSummary;

export {
  make ,
}
/* react Not a pure module */
