// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/core/styles";

var theme = Styles.createTheme({
      palette: {
        primary: {
          main: "#8fe830"
        }
      }
    });

function ExampleThemeProvider(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Core.Button, {
                      children: "Default Primary Color",
                      color: "primary",
                      variant: "outlined"
                    }),
                " ",
                JsxRuntime.jsx(Styles.ThemeProvider, {
                      children: JsxRuntime.jsx(Core.Button, {
                            children: "Themed Primary Color",
                            color: "primary",
                            variant: "outlined"
                          }),
                      theme: theme
                    })
              ]
            });
}

var make = ExampleThemeProvider;

export {
  theme ,
  make ,
}
/* theme Not a pure module */
