// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@mui/material/styles";

function theme(outerTheme) {
  var newrecord = Caml_obj.obj_dup(outerTheme);
  return Styles.createTheme((newrecord.palette = {
                primary: {
                  main: "#8fe830"
                }
              }, newrecord));
}

function ExampleThemeProvider(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx((function (prim) {
                        return Material.Button(prim);
                      }), {
                      children: "Default Primary Color",
                      color: "primary",
                      variant: "outlined"
                    }),
                " ",
                JsxRuntime.jsx((function (prim) {
                        return Styles.ThemeProvider(prim);
                      }), {
                      children: JsxRuntime.jsx((function (prim) {
                              return Material.Button(prim);
                            }), {
                            children: "Themed Primary Color",
                            color: "primary",
                            variant: "outlined"
                          }),
                      theme: theme
                    })
              ]
            });
}

var make = ExampleThemeProvider;

export {
  theme ,
  make ,
}
/* @mui/material Not a pure module */
