// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles({
      root: {
        backgroundColor: "#FFFFFF",
        maxHeight: "300px",
        maxWidth: "360px",
        overflow: "auto",
        position: "relative",
        width: "100%"
      },
      listSection: {
        backgroundColor: "inherit"
      },
      ul: {
        backgroundColor: "inherit",
        padding: "0"
      }
    });

function ExampleList(props) {
  var classes = useStyles();
  var subheader = JsxRuntime.jsx("li", {});
  return JsxRuntime.jsx(Core.Card, {
              children: Caml_option.some(JsxRuntime.jsxs(Core.Card, {
                        children: [
                          JsxRuntime.jsx(Core.CardHeader, {
                                subheader: "A Subtitle",
                                title: "Example Title"
                              }),
                          JsxRuntime.jsx(Core.CardContent, {
                                children: Caml_option.some(JsxRuntime.jsx(Core.List, {
                                          children: Caml_option.some($$Array.map((function (sectionId) {
                                                      return JsxRuntime.jsx("li", {
                                                                  children: JsxRuntime.jsx("ul", {
                                                                        children: $$Array.append([JsxRuntime.jsx(Core.ListSubheader, {
                                                                                    children: Caml_option.some("I'm sticky " + String(sectionId))
                                                                                  }, "header")], $$Array.map((function (item) {
                                                                                    return JsxRuntime.jsx(Core.ListItem, {
                                                                                                children: Caml_option.some(JsxRuntime.jsx(Core.ListItemText, {
                                                                                                          children: Caml_option.some("Item " + String(item))
                                                                                                        }))
                                                                                              }, "item-" + (String(sectionId) + ("-" + String(item))));
                                                                                  }), [
                                                                                  0,
                                                                                  1,
                                                                                  2
                                                                                ])),
                                                                        className: classes.ul
                                                                      }),
                                                                  className: classes.listSection
                                                                }, "section-" + String(sectionId));
                                                    }), [
                                                    0,
                                                    1,
                                                    2,
                                                    3,
                                                    4
                                                  ])),
                                          className: classes.root,
                                          subheader: Caml_option.some(subheader)
                                        }))
                              }),
                          JsxRuntime.jsx(Core.CardActions, {
                                children: Caml_option.some(JsxRuntime.jsx(Core.Button, {
                                          children: "Go to example",
                                          color: "primary",
                                          href: "#/example/route",
                                          variant: "contained"
                                        }))
                              })
                        ]
                      }))
            });
}

var make = ExampleList;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
