// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import Button from "@mui/material/Button";
import * as Styles from "@mui/material/styles";

function ExampleStylingCss(props) {
  return JsxRuntime.jsx(Styles.StyledEngineProvider, {
              injectFirst: true,
              children: JsxRuntime.jsx(Button, {
                    className: "my-global-class-name",
                    children: "Hello, plain CSS & MUI!",
                    onClick: (function (prim) {
                        
                      }),
                    color: "primary"
                  })
            });
}

var make = ExampleStylingCss;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
