// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import TextField from "@mui/material/TextField";

function ExampleTextFieldSize(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(TextField, {
                      placeholder: "None",
                      fullWidth: true,
                      variant: "outlined"
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(TextField, {
                      placeholder: "Medium",
                      fullWidth: true,
                      size: "medium",
                      variant: "outlined"
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(TextField, {
                      placeholder: "Small",
                      fullWidth: true,
                      size: "small",
                      variant: "outlined"
                    })
              ]
            });
}

var make = ExampleTextFieldSize;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
