// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";

function ExampleSkeleton(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Material.Skeleton, {
                      variant: "text"
                    }),
                JsxRuntime.jsx(Material.Skeleton, {
                      height: 40,
                      variant: "circular",
                      width: 40
                    }),
                JsxRuntime.jsx(Material.Skeleton, {
                      height: 118,
                      variant: "rectangular",
                      width: 210
                    })
              ]
            });
}

var make = ExampleSkeleton;

export {
  make ,
}
/* @mui/material Not a pure module */
