// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@mui/styles";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";
import * as Colors from "@mui/material/colors";

var useStyles = Styles.makeStyles({
      fontSize: {
        fontSize: "30px"
      },
      bgColor: {
        backgroundColor: Colors.red[300]
      }
    });

function ExampleClassOverride(props) {
  var classes = useStyles(undefined);
  return JsxRuntime.jsx((function (prim) {
                return Material.Button(prim);
              }), {
              children: "Example Button",
              classes: {
                root: classes.fontSize,
                containedPrimary: classes.bgColor
              },
              color: "primary",
              variant: "contained"
            });
}

var make = ExampleClassOverride;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
