// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function ExampleTextFieldSize(Props) {
  return React.createElement("div", undefined, React.createElement(Core.TextField, {
                  fullWidth: true,
                  placeholder: "None",
                  variant: "outlined"
                }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.TextField, {
                  fullWidth: true,
                  placeholder: "Medium",
                  size: "medium",
                  variant: "outlined"
                }), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Core.TextField, {
                  fullWidth: true,
                  placeholder: "Small",
                  size: "small",
                  variant: "outlined"
                }));
}

var make = ExampleTextFieldSize;

export {
  make ,
}
/* react Not a pure module */
