// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import Menu from "@mui/material/Menu";
import MenuItem from "@mui/material/MenuItem";

function ExampleMenu(props) {
  return JsxRuntime.jsxs(Menu, {
              id: "menu",
              component: "nav",
              open: true,
              children: [
                JsxRuntime.jsx(MenuItem, {
                      id: "simple-menu-item-1",
                      children: "Profile"
                    }),
                JsxRuntime.jsx(MenuItem, {
                      id: "simple-menu-item-2",
                      children: "My account"
                    }),
                JsxRuntime.jsx(MenuItem, {
                      id: "simple-menu-item-3",
                      children: "Logout"
                    })
              ]
            });
}

var make = ExampleMenu;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
