// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";

function ExampleRadioGroup(props) {
  var match = React.useState(function () {
        return "Yes";
      });
  var setState = match[1];
  return JsxRuntime.jsxs((function (prim) {
                return Material.RadioGroup(prim);
              }), {
              children: [
                JsxRuntime.jsx((function (prim) {
                        return Material.FormControlLabel(prim);
                      }), {
                      control: JsxRuntime.jsx((function (prim) {
                              return Material.Radio(prim);
                            }), {}),
                      label: "Yes",
                      value: "Yes"
                    }),
                JsxRuntime.jsx((function (prim) {
                        return Material.FormControlLabel(prim);
                      }), {
                      control: JsxRuntime.jsx((function (prim) {
                              return Material.Radio(prim);
                            }), {}),
                      label: "No",
                      value: "No"
                    }),
                JsxRuntime.jsx((function (prim) {
                        return Material.FormControlLabel(prim);
                      }), {
                      control: JsxRuntime.jsx((function (prim) {
                              return Material.Radio(prim);
                            }), {}),
                      label: "Maybe",
                      value: "Maybe"
                    })
              ],
              name: "answer",
              onChange: (function (e, param) {
                  var value = e.target.value;
                  setState(function (param) {
                        return value;
                      });
                }),
              value: Caml_option.some(match[0])
            });
}

var make = ExampleRadioGroup;

export {
  make ,
}
/* react Not a pure module */
