// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";
import SupervisedUserCircle from "@material-ui/icons/SupervisedUserCircle";
import SupervisedUserCircleSharp from "@material-ui/icons/SupervisedUserCircleSharp";
import SupervisedUserCircleRounded from "@material-ui/icons/SupervisedUserCircleRounded";
import SupervisedUserCircleTwoTone from "@material-ui/icons/SupervisedUserCircleTwoTone";
import SupervisedUserCircleOutlined from "@material-ui/icons/SupervisedUserCircleOutlined";

var Filled = {};

var Outlined = {};

var Rounded = {};

var Sharp = {};

var TwoTone = {};

var SupervisedUserCircle$1 = {
  Filled: Filled,
  Outlined: Outlined,
  Rounded: Rounded,
  Sharp: Sharp,
  TwoTone: TwoTone
};

function rs(prim) {
  return prim;
}

function ExampleIcons(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement(Core.Typography, {
                      children: "Icon Types:",
                      variant: "h6"
                    }), React.createElement(Core.Tooltip, {
                      arrow: true,
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircle, {})),
                      placement: "top",
                      title: "Default"
                    }), React.createElement(Core.Tooltip, {
                      arrow: true,
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircleOutlined, {})),
                      placement: "left",
                      title: "Outlined"
                    }), React.createElement(Core.Tooltip, {
                      arrow: true,
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircleRounded, {})),
                      placement: "top-end",
                      title: "Rounded"
                    }), React.createElement(Core.Tooltip, {
                      arrow: true,
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircleTwoTone, {})),
                      placement: "bottom",
                      title: "TwoTone"
                    }), React.createElement(Core.Tooltip, {
                      arrow: true,
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircleSharp, {})),
                      placement: "right",
                      title: "Sharp"
                    })), React.createElement("hr", undefined), React.createElement("div", undefined, React.createElement(Core.Typography, {
                      children: "Icon Colors:",
                      variant: "h6"
                    }), React.createElement(Core.Tooltip, {
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircle, {
                                color: "primary"
                              })),
                      title: "Primary"
                    }), React.createElement(Core.Tooltip, {
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircle, {
                                color: "secondary"
                              })),
                      title: "Secondary"
                    })), React.createElement("hr", undefined), React.createElement("div", undefined, React.createElement(Core.Typography, {
                      children: "Icon Sizes:",
                      variant: "h6"
                    }), React.createElement(Core.Tooltip, {
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircle, {
                                fontSize: "large"
                              })),
                      title: "Large"
                    }), React.createElement(Core.Tooltip, {
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircle, {
                                fontSize: "default"
                              })),
                      title: "Default"
                    }), React.createElement(Core.Tooltip, {
                      children: React.createElement("span", undefined, React.createElement(SupervisedUserCircle, {
                                fontSize: "small"
                              })),
                      title: "Small"
                    })));
}

var make = ExampleIcons;

export {
  SupervisedUserCircle$1 as SupervisedUserCircle,
  rs ,
  make ,
}
/* react Not a pure module */
