// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/core/styles";

function ExampleStylingTailwind(props) {
  return JsxRuntime.jsx(Styles.StylesProvider, {
              injectFirst: true,
              children: JsxRuntime.jsx(Core.Button, {
                    onClick: (function (prim) {
                        
                      }),
                    children: "Hello, Tailwind & MUI!",
                    classes: {
                      root: "normal-case justify-start"
                    },
                    color: "primary"
                  })
            });
}

var make = ExampleStylingTailwind;

export {
  make ,
}
/* @material-ui/core Not a pure module */
