// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Tab from "@mui/material/Tab";
import * as JsxRuntime from "react/jsx-runtime";
import Tabs from "@mui/material/Tabs";
import Paper from "@mui/material/Paper";

function ExampleTabs(props) {
  var match = React.useReducer((function (param, v) {
          return v;
        }), 2);
  var setValue = match[1];
  var handleChange = function (param, newValue) {
    setValue(newValue);
  };
  return JsxRuntime.jsx(Paper, {
              square: true,
              children: Caml_option.some(JsxRuntime.jsxs(Tabs, {
                        children: [
                          JsxRuntime.jsx(Tab, {
                                label: "Active"
                              }),
                          JsxRuntime.jsx(Tab, {
                                disabled: true,
                                label: "Disabled"
                              }),
                          JsxRuntime.jsx(Tab, {
                                label: "Active"
                              })
                        ],
                        indicatorColor: "primary",
                        onChange: handleChange,
                        textColor: "primary",
                        value: match[0]
                      }))
            });
}

var make = ExampleTabs;

export {
  make ,
}
/* react Not a pure module */
