// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";

function ExamplePagination(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Material.Pagination, {
                      count: 10
                    }),
                JsxRuntime.jsx(Material.Pagination, {
                      count: 10,
                      color: "primary"
                    }),
                JsxRuntime.jsx(Material.Pagination, {
                      count: 10,
                      color: "secondary"
                    }),
                JsxRuntime.jsx(Material.Pagination, {
                      count: 10,
                      disabled: true
                    })
              ]
            });
}

var make = ExamplePagination;

export {
  make ,
}
/* @mui/material Not a pure module */
