// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactDOMStyle from "@rescript/react/src/ReactDOMStyle.bs.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/core/styles";
import SupervisedUserCircle from "@material-ui/icons/SupervisedUserCircle";

var theme = Styles.createTheme({
      overrides: {
        MuiButton: {
          outlined: ReactDOMStyle.unsafeAddProp({
                color: "gray",
                fontSize: "12px",
                fontWeight: "300"
              }, "& svg", {
                fontSize: "16px",
                marginRight: "15px"
              })
        }
      }
    });

var SupervisedUserCircleIcon = {};

function ExampleThemeProviderOverride(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Styles.ThemeProvider, {
                    children: JsxRuntime.jsxs(Core.Button, {
                          children: [
                            JsxRuntime.jsx(SupervisedUserCircle, {}),
                            "Overriden Outline Styles"
                          ],
                          color: "secondary",
                          variant: "outlined"
                        }),
                    theme: theme
                  })
            });
}

var make = ExampleThemeProviderOverride;

export {
  theme ,
  SupervisedUserCircleIcon ,
  make ,
}
/* theme Not a pure module */
