// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";

function ExampleRating(props) {
  var match = React.useReducer((function (param, v) {
          return v;
        }), 2);
  var setValue = match[1];
  var value = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs(Material.Box, {
                      borderColor: "transparent",
                      mb: 3,
                      children: [
                        JsxRuntime.jsx(Material.Typography, {
                              component: "legend",
                              children: "Controlled"
                            }),
                        JsxRuntime.jsx(Material.Rating, {
                              name: "simple-controlled",
                              onChange: (function (param, newValue) {
                                  if (typeof newValue !== "number") {
                                    return ;
                                  } else {
                                    return setValue(newValue);
                                  }
                                }),
                              value: value
                            })
                      ],
                      component: "fieldset"
                    }),
                JsxRuntime.jsxs(Material.Box, {
                      borderColor: "transparent",
                      mb: 3,
                      children: [
                        JsxRuntime.jsx(Material.Typography, {
                              component: "legend",
                              children: "Read only"
                            }),
                        JsxRuntime.jsx(Material.Rating, {
                              name: "read-only",
                              readOnly: true,
                              value: value
                            })
                      ],
                      component: "fieldset"
                    }),
                JsxRuntime.jsxs(Material.Box, {
                      borderColor: "transparent",
                      mb: 3,
                      children: [
                        JsxRuntime.jsx(Material.Typography, {
                              component: "legend",
                              children: "Disabled"
                            }),
                        JsxRuntime.jsx(Material.Rating, {
                              disabled: true,
                              name: "disabled",
                              value: value
                            })
                      ],
                      component: "fieldset"
                    }),
                JsxRuntime.jsxs(Material.Box, {
                      borderColor: "transparent",
                      mb: 3,
                      children: [
                        JsxRuntime.jsx(Material.Typography, {
                              component: "legend",
                              children: "Pristine"
                            }),
                        JsxRuntime.jsx(Material.Rating, {
                              name: "pristine",
                              value: 0
                            })
                      ],
                      component: "fieldset"
                    })
              ]
            });
}

var make = ExampleRating;

export {
  make ,
}
/* react Not a pure module */
