// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MaterialUi_Box from "rescript-material-ui/src/MaterialUi_Box.bs.js";
import * as Core from "@material-ui/core";

function ExampleBox(Props) {
  return React.createElement(Core.Box, {
              component: MaterialUi_Box.Component.string("span"),
              style: {
                boxSizing: "border-box"
              },
              children: "Testbox",
              bgcolor: MaterialUi_Box.Value.paletteColor("background.paper"),
              borderColor: MaterialUi_Box.Value.paletteColor("error.main"),
              borderTop: MaterialUi_Box.Value.$$int(1),
              color: MaterialUi_Box.Value.paletteColor("text.secondary"),
              fontSize: MaterialUi_Box.Value.string("30px"),
              m: MaterialUi_Box.Value.array([
                    MaterialUi_Box.Value.$$int(2),
                    MaterialUi_Box.Value.$$int(5)
                  ]),
              p: MaterialUi_Box.Value.breakpointObj(MaterialUi_Box.BreakpointObj.make(undefined, Caml_option.some(MaterialUi_Box.Value.$$int(2)), Caml_option.some(MaterialUi_Box.Value.$$int(5)), undefined, undefined, undefined))
            });
}

var make = ExampleBox;

export {
  make ,
  
}
/* react Not a pure module */
