// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";

function ExampleBox(props) {
  return JsxRuntime.jsx((function (prim) {
                return Material.Box(prim);
              }), {
              style: {
                boxSizing: "border-box"
              },
              borderColor: "error.main",
              borderTop: 1,
              bgcolor: "background.paper",
              color: "text.secondary",
              m: [
                2,
                5
              ],
              p: {
                sm: 2,
                md: 5
              },
              fontSize: "30px",
              children: "Testbox",
              component: "span"
            });
}

var make = ExampleBox;

export {
  make ,
}
/* @mui/material Not a pure module */
