// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Alert from "@mui/material/Alert";
import Badge from "@mui/material/Badge";
import Switch from "@mui/material/Switch";
import Checkbox from "@mui/material/Checkbox";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

function ExampleSlots(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Slots and SlotProps Examples (MUI v6):"
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "body2",
                      children: "The slots/slotProps pattern allows customizing internal component parts.",
                      sx: {
                        marginBottom: "16px"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Alert with slotProps:",
                      sx: {
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(Alert, {
                              id: "alert-slotprops-basic",
                              children: "Alert with custom root and message styles via slotProps",
                              severity: "info",
                              slotProps: {
                                root: {
                                  style: {
                                    border: "2px solid blue"
                                  }
                                },
                                message: {
                                  style: {
                                    fontStyle: "italic"
                                  }
                                }
                              }
                            }),
                        JsxRuntime.jsx(Alert, {
                              id: "alert-slotprops-icon",
                              children: "Alert with larger icon via slotProps",
                              severity: "success",
                              slotProps: {
                                icon: {
                                  style: {
                                    fontSize: "32px"
                                  }
                                }
                              }
                            })
                      ],
                      sx: {
                        display: "flex",
                        flexDirection: "column",
                        gap: "8px",
                        marginBottom: "16px"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Badge with slotProps:"
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(Badge, {
                              id: "badge-slotprops-basic",
                              badgeContent: "5",
                              children: Caml_option.some(JsxRuntime.jsx(Box, {
                                        sx: {
                                          borderRadius: "4px",
                                          bgcolor: "grey.300",
                                          height: "40px",
                                          width: "40px"
                                        }
                                      })),
                              slotProps: {
                                badge: {
                                  style: {
                                    transform: "scale(1.2)"
                                  }
                                }
                              },
                              color: "primary"
                            }),
                        JsxRuntime.jsx(Badge, {
                              id: "badge-slotprops-root",
                              badgeContent: "99+",
                              children: Caml_option.some(JsxRuntime.jsx(Box, {
                                        sx: {
                                          borderRadius: "4px",
                                          bgcolor: "grey.400",
                                          height: "40px",
                                          width: "40px"
                                        }
                                      })),
                              slotProps: {
                                root: {
                                  style: {
                                    backgroundColor: "#f5f5f5",
                                    padding: "8px"
                                  }
                                }
                              },
                              color: "error"
                            })
                      ],
                      sx: {
                        display: "flex",
                        alignItems: "center",
                        gap: "24px",
                        marginBottom: "16px"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "TextField with slotProps:"
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(TextField, {
                              id: "textfield-slotprops-label",
                              label: "Styled Label",
                              slotProps: {
                                inputLabel: {
                                  style: {
                                    color: "purple",
                                    fontWeight: "bold"
                                  }
                                }
                              },
                              variant: "outlined"
                            }),
                        JsxRuntime.jsx(TextField, {
                              id: "textfield-slotprops-helper",
                              helperText: "Custom styled helper text",
                              label: "With Helper",
                              slotProps: {
                                formHelperText: {
                                  style: {
                                    color: "green",
                                    fontStyle: "italic"
                                  }
                                }
                              },
                              variant: "outlined"
                            }),
                        JsxRuntime.jsx(TextField, {
                              id: "textfield-slotprops-input",
                              defaultValue: "Custom input style",
                              label: "Styled Input",
                              slotProps: {
                                htmlInput: {
                                  style: {
                                    backgroundColor: "#fff8e1"
                                  }
                                }
                              },
                              variant: "outlined"
                            })
                      ],
                      sx: {
                        display: "flex",
                        flexDirection: "column",
                        gap: "16px",
                        maxWidth: "300px"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Checkbox with slotProps:",
                      sx: {
                        marginTop: "16px"
                      }
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(Checkbox, {
                              id: "checkbox-slotprops",
                              defaultChecked: true,
                              slotProps: {
                                input: {
                                  "aria-label": "Custom aria label via slotProps"
                                }
                              }
                            }),
                        JsxRuntime.jsx(Typography, {
                              component: "span",
                              variant: "caption",
                              children: "Checkbox with custom input props via slotProps"
                            })
                      ],
                      sx: {
                        marginBottom: "16px"
                      }
                    }),
                JsxRuntime.jsx(Typography, {
                      variant: "subtitle2",
                      children: "Switch with slotProps:"
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(Switch, {
                              id: "switch-slotprops",
                              defaultChecked: true,
                              slotProps: {
                                input: {
                                  "aria-label": "Switch with custom aria label"
                                }
                              }
                            }),
                        JsxRuntime.jsx(Typography, {
                              component: "span",
                              variant: "caption",
                              children: "Switch with custom input props via slotProps"
                            })
                      ]
                    })
              ]
            });
}

var make = ExampleSlots;

export {
  make ,
}
/* @mui/material/Box Not a pure module */
