// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";

function ExampleGrid$Item(props) {
  return JsxRuntime.jsx(Paper, {
              sx: [{
                  color: "text.secondary",
                  p: 2,
                  textAlign: "center"
                }],
              children: Caml_option.some(props.children)
            });
}

var Item = {
  make: ExampleGrid$Item
};

function ExampleGrid(props) {
  return JsxRuntime.jsxs(Box, {
              children: [
                JsxRuntime.jsx(Typography, {
                      gutterBottom: true,
                      variant: "h6",
                      children: "Basic Grid"
                    }),
                JsxRuntime.jsxs(Grid, {
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=8"
                                      })),
                              item: true,
                              xs: 8
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=4"
                                      })),
                              item: true,
                              xs: 4
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=4"
                                      })),
                              item: true,
                              xs: 4
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=8"
                                      })),
                              item: true,
                              xs: 8
                            })
                      ],
                      container: true,
                      spacing: 2
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Typography, {
                      gutterBottom: true,
                      variant: "h6",
                      children: "Responsive Grid"
                    }),
                JsxRuntime.jsxs(Grid, {
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=6 md=8"
                                      })),
                              item: true,
                              md: 8,
                              xs: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=6 md=4"
                                      })),
                              item: true,
                              md: 4,
                              xs: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=6 md=4"
                                      })),
                              item: true,
                              md: 4,
                              xs: 6
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "xs=6 md=8"
                                      })),
                              item: true,
                              md: 8,
                              xs: 6
                            })
                      ],
                      container: true,
                      spacing: 2
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Typography, {
                      gutterBottom: true,
                      variant: "h6",
                      children: "Grid Direction Column"
                    }),
                JsxRuntime.jsxs(Grid, {
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "Column 1"
                                      })),
                              item: true
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "Column 2"
                                      })),
                              item: true
                            })
                      ],
                      container: true,
                      direction: "column",
                      spacing: 2
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Typography, {
                      gutterBottom: true,
                      variant: "h6",
                      children: "Alignment - Center"
                    }),
                JsxRuntime.jsx(Grid, {
                      alignItems: "center",
                      justifyContent: "center",
                      children: Caml_option.some(JsxRuntime.jsx(Grid, {
                                children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                          children: "Centered"
                                        })),
                                item: true
                              })),
                      container: true,
                      spacing: 2,
                      sx: {
                        minHeight: "100px"
                      }
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsx(Typography, {
                      gutterBottom: true,
                      variant: "h6",
                      children: "Alignment - Space Between"
                    }),
                JsxRuntime.jsxs(Grid, {
                      justifyContent: "space-between",
                      children: [
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "Left"
                                      })),
                              item: true,
                              xs: 5
                            }),
                        JsxRuntime.jsx(Grid, {
                              children: Caml_option.some(JsxRuntime.jsx(ExampleGrid$Item, {
                                        children: "Right"
                                      })),
                              item: true,
                              xs: 5
                            })
                      ],
                      container: true,
                      spacing: 2,
                      sx: {
                        minHeight: "100px"
                      }
                    })
              ],
              sx: {
                flexGrow: 1
              }
            });
}

var make = ExampleGrid;

export {
  Item ,
  make ,
}
/* @mui/material/Box Not a pure module */
