// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import Icon from "@mui/material/Icon";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";

function ExampleButtons(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(IconButton, {
                      id: "icon-button-1",
                      children: Caml_option.some(JsxRuntime.jsx(Icon, {
                                id: "icon-1",
                                children: "AddCircleFilled"
                              })),
                      color: "primary"
                    }),
                JsxRuntime.jsx(Button, {
                      id: "button-1",
                      children: "Text Button",
                      color: "primary",
                      variant: "text"
                    }),
                JsxRuntime.jsx(Button, {
                      id: "button-2",
                      children: "Outlined Button",
                      color: "primary",
                      variant: "outlined"
                    }),
                JsxRuntime.jsx(Button, {
                      id: "button-3",
                      children: "Contained Button",
                      color: "primary",
                      variant: "contained"
                    })
              ]
            });
}

var make = ExampleButtons;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
