// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import Input from "@mui/material/Input";
import Select from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import InputLabel from "@mui/material/InputLabel";
import FilledInput from "@mui/material/FilledInput";
import FormControl from "@mui/material/FormControl";
import OutlinedInput from "@mui/material/OutlinedInput";
import FormHelperText from "@mui/material/FormHelperText";

function getSpacing(theme, num) {
  return String(theme.spacing(num)) + "px";
}

function ExampleSelect(props) {
  var match = React.useReducer((function (param, v) {
          return v;
        }), {
        age: "",
        name: "hai"
      });
  var setValues = match[1];
  var values = match[0];
  var match$1 = React.useReducer((function (param, v) {
          return v;
        }), undefined);
  var setInputLabelEl = match$1[1];
  var inputLabelEl = match$1[0];
  var inputLabel = React.useCallback((function (el) {
          setInputLabelEl((el == null) ? undefined : Caml_option.some(el));
        }), []);
  var match$2 = React.useReducer((function (param, l) {
          return l;
        }), 0);
  var setLabelWidth = match$2[1];
  React.useEffect((function () {
          if (inputLabelEl !== undefined) {
            setLabelWidth(Caml_option.valFromOption(inputLabelEl).offsetWidth);
          }
          
        }), [inputLabelEl]);
  var handleChangeAge = function (e, param) {
    setValues({
          age: e.target.value,
          name: values.name
        });
  };
  var handleChangeName = function (e, param) {
    setValues({
          age: values.age,
          name: e.target.value
        });
  };
  return JsxRuntime.jsx("form", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Age",
                                    htmlFor: "age-simple"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    inputProps: {
                                      id: "age-simple",
                                      name: "age"
                                    },
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    onChange: handleChangeAge
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Age",
                                    htmlFor: "age-helper"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(Input, {
                                              id: "age-helper",
                                              name: "age"
                                            })),
                                    onChange: handleChangeAge
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Some important helper text"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsxs(Select, {
                                    name: "age",
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    displayEmpty: true,
                                    onChange: handleChangeAge
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Without label"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Age",
                                    shrink: true,
                                    htmlFor: "age-label-placeholder"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    name: "age",
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    displayEmpty: true,
                                    input: Caml_option.some(JsxRuntime.jsx(Input, {
                                              id: "age-label-placeholder",
                                              name: "age"
                                            })),
                                    onChange: handleChangeAge
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Label + placeholder"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Name",
                                    htmlFor: "name-disabled"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    value: values.name,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Hai",
                                            value: "hai"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Olivier",
                                            value: "olivier"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Kevin",
                                            value: "kevin"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(Input, {
                                              id: "name-disabled",
                                              name: "name"
                                            })),
                                    onChange: handleChangeName
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Disabled"
                                  })
                            ],
                            disabled: true
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Name",
                                    htmlFor: "name-error"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    name: "name",
                                    value: values.name,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Hai",
                                            value: "hai"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Olivier",
                                            value: "olivier"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Kevin",
                                            value: "kevin"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(Input, {
                                              id: "name-error"
                                            })),
                                    onChange: handleChangeName,
                                    renderValue: (function (value) {
                                        return "⚠️  - " + value;
                                      })
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Error"
                                  })
                            ],
                            error: true
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Name",
                                    htmlFor: "name-readonly"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    value: values.name,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Hai",
                                            value: "hai"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Olivier",
                                            value: "olivier"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Kevin",
                                            value: "kevin"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(Input, {
                                              id: "name-readonly",
                                              name: "name",
                                              readOnly: true
                                            })),
                                    onChange: handleChangeName
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Read only"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Age",
                                    htmlFor: "age-auto-width"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    value: values.age,
                                    autoWidth: true,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(Input, {
                                              id: "age-auto-width",
                                              name: "age"
                                            })),
                                    onChange: handleChangeAge
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Auto width"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsxs(Select, {
                                    name: "age",
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Placeholder",
                                            disabled: true,
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    displayEmpty: true,
                                    onChange: handleChangeAge
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Placeholder"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Age",
                                    htmlFor: "age-required"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    inputProps: {
                                      id: "age-required"
                                    },
                                    name: "age",
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    onChange: handleChangeAge
                                  }),
                              JsxRuntime.jsx(FormHelperText, {
                                    children: "Required"
                                  })
                            ],
                            required: true
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    ref: Caml_option.some(inputLabel),
                                    children: "Age",
                                    htmlFor: "outlined-age-simple"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(OutlinedInput, {
                                              id: "outlined-age-simple",
                                              name: "age",
                                              label: Caml_option.some(JsxRuntime.jsx("div", {
                                                        width: String(match$2[0])
                                                      }))
                                            })),
                                    onChange: handleChangeAge
                                  })
                            ],
                            variant: "outlined"
                          }),
                      JsxRuntime.jsxs(FormControl, {
                            children: [
                              JsxRuntime.jsx(InputLabel, {
                                    children: "Age",
                                    htmlFor: "filled-age-simple"
                                  }),
                              JsxRuntime.jsxs(Select, {
                                    value: values.age,
                                    children: [
                                      JsxRuntime.jsx(MenuItem, {
                                            children: Caml_option.some(JsxRuntime.jsx("em", {
                                                      children: "None"
                                                    })),
                                            value: ""
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Ten",
                                            value: "10"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Twenty",
                                            value: "20"
                                          }),
                                      JsxRuntime.jsx(MenuItem, {
                                            children: "Thirty",
                                            value: "30"
                                          })
                                    ],
                                    input: Caml_option.some(JsxRuntime.jsx(FilledInput, {
                                              id: "filled-age-simple",
                                              name: "age"
                                            })),
                                    onChange: handleChangeAge
                                  })
                            ],
                            variant: "filled"
                          })
                    ]
                  }),
              autoComplete: "off"
            });
}

var make = ExampleSelect;

export {
  getSpacing ,
  make ,
}
/* react Not a pure module */
