// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/core/styles";

function ExampleStylingCss(Props) {
  return React.createElement(Styles.StylesProvider, {
              injectFirst: true,
              children: React.createElement(Core.Button, {
                    onClick: (function (prim) {
                        
                      }),
                    children: "Hello, plain CSS & MUI!",
                    className: "my-global-class-name",
                    color: "primary"
                  })
            });
}

var make = ExampleStylingCss;

export {
  make ,
}
/* react Not a pure module */
