// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@mui/styles";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles$1 from "@mui/material/styles";

var theme = Styles$1.createTheme({
      palette: {
        primary: {
          main: "#8fe830"
        }
      }
    });

function ExampleThemeProvider(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx((function (prim) {
                        return Material.Button(prim);
                      }), {
                      children: "Default Primary Color",
                      color: "primary",
                      variant: "outlined"
                    }),
                " ",
                JsxRuntime.jsx(Styles.ThemeProvider, {
                      children: JsxRuntime.jsx((function (prim) {
                              return Material.Button(prim);
                            }), {
                            children: "Themed Primary Color",
                            color: "primary",
                            variant: "outlined"
                          }),
                      theme: theme
                    })
              ]
            });
}

var make = ExampleThemeProvider;

export {
  theme ,
  make ,
}
/* theme Not a pure module */
