// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function ExampleBox(Props) {
  return React.createElement(Core.Box, {
              component: "span",
              style: {
                boxSizing: "border-box"
              },
              children: "Testbox",
              bgcolor: "background.paper",
              borderColor: "error.main",
              borderTop: 1,
              color: "text.secondary",
              fontSize: "30px",
              m: [
                2,
                5
              ],
              p: {
                sm: 2,
                md: 5
              }
            });
}

var make = ExampleBox;

export {
  make ,
  
}
/* react Not a pure module */
