// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/core/styles";

var categoryButton = CssJs.style([
      CssJs.textTransform("none"),
      CssJs.justifyContent("flexStart")
    ]);

var Styles$1 = {
  categoryButton: categoryButton
};

function ExampleStylingBsCss(Props) {
  return React.createElement(Styles.StylesProvider, {
              injectFirst: true,
              children: React.createElement(Core.Button, {
                    onClick: (function (prim) {
                        
                      }),
                    children: "Hello, BS-CSS & MUI!",
                    classes: {
                      root: categoryButton
                    },
                    color: "primary"
                  })
            });
}

var make = ExampleStylingBsCss;

export {
  Styles$1 as Styles,
  make ,
}
/* categoryButton Not a pure module */
