// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";

function ExampleButtonLoading(props) {
  var match = React.useState(function () {
        return false;
      });
  var setLoading = match[1];
  var handleClick = function (param) {
    setLoading(function (param) {
          return true;
        });
    setTimeout((function () {
            setLoading(function (param) {
                  return false;
                });
          }), 2000);
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Button Loading Examples:"
                    }),
                JsxRuntime.jsxs(Box, {
                      children: [
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-basic",
                              children: "Click to Load",
                              onClick: handleClick,
                              loading: match[0] ? true : false,
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Typography, {
                              variant: "subtitle2",
                              children: "Loading Positions:"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-center",
                              children: "Center (default)",
                              loading: true,
                              loadingPosition: "center",
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-start",
                              children: "Start Position",
                              loading: true,
                              loadingPosition: "start",
                              startIcon: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: ">"
                                      })),
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-end",
                              children: "End Position",
                              endIcon: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: ">"
                                      })),
                              loading: true,
                              loadingPosition: "end",
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Typography, {
                              variant: "subtitle2",
                              children: "Custom Loading Indicator:"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-custom",
                              children: "Submit",
                              loading: true,
                              loadingIndicator: Caml_option.some(JsxRuntime.jsx("span", {
                                        children: "Loading..."
                                      })),
                              variant: "outlined"
                            }),
                        JsxRuntime.jsx(Typography, {
                              variant: "subtitle2",
                              children: "Loading with Variants:"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-text",
                              children: "Text",
                              loading: true,
                              variant: "text"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-outlined",
                              children: "Outlined",
                              loading: true,
                              variant: "outlined"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-contained",
                              children: "Contained",
                              loading: true,
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Typography, {
                              variant: "subtitle2",
                              children: "Loading with Colors:"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-primary",
                              children: "Primary",
                              color: "primary",
                              loading: true,
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-secondary",
                              children: "Secondary",
                              color: "secondary",
                              loading: true,
                              variant: "contained"
                            }),
                        JsxRuntime.jsx(Button, {
                              id: "button-loading-success",
                              children: "Success",
                              color: "success",
                              loading: true,
                              variant: "contained"
                            })
                      ],
                      sx: {
                        display: "flex",
                        flexDirection: "column",
                        gap: "16px",
                        maxWidth: "300px"
                      }
                    })
              ]
            });
}

var make = ExampleButtonLoading;

export {
  make ,
}
/* react Not a pure module */
