// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles(function (theme) {
      return {
              alignRight: {
                textAlign: "right",
                width: "100%"
              },
              background: {
                backgroundColor: theme.palette.primary.main,
                color: theme.palette.common.white
              }
            };
    });

function ExampleStyles(Props) {
  var classes = useStyles();
  return React.createElement("div", undefined, React.createElement("div", {
                  className: classes.alignRight
                }, "Example text - aligned to the right"), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("div", {
                  className: classes.background
                }, "Example text on a background coming from the Mui Theme object"));
}

var make = ExampleStyles;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
