// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import Box from "@mui/material/Box";
import * as JsxRuntime from "react/jsx-runtime";
import Switch from "@mui/material/Switch";
import FormGroup from "@mui/material/FormGroup";
import Typography from "@mui/material/Typography";
import FormControlLabel from "@mui/material/FormControlLabel";

function ExampleSwitch(props) {
  var match = React.useState(function () {
        return true;
      });
  var setChecked = match[1];
  var handleChange = function (_event, newChecked) {
    setChecked(function (param) {
          return newChecked;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Typography, {
                      variant: "h6",
                      children: "Switch Examples:"
                    }),
                JsxRuntime.jsx(Box, {
                      children: Caml_option.some(JsxRuntime.jsxs(FormGroup, {
                                children: [
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-default",
                                              defaultChecked: true
                                            }),
                                        label: "Default"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-controlled",
                                              checked: match[0],
                                              onChange: handleChange
                                            }),
                                        label: "Controlled"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-disabled",
                                              disabled: true
                                            }),
                                        label: "Disabled"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-disabled-checked",
                                              checked: true,
                                              disabled: true
                                            }),
                                        label: "Disabled Checked"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-color-primary",
                                              color: "primary",
                                              defaultChecked: true
                                            }),
                                        label: "Primary Color"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-color-secondary",
                                              color: "secondary",
                                              defaultChecked: true
                                            }),
                                        label: "Secondary Color"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-color-success",
                                              color: "success",
                                              defaultChecked: true
                                            }),
                                        label: "Success Color"
                                      }),
                                  JsxRuntime.jsx(FormControlLabel, {
                                        control: JsxRuntime.jsx(Switch, {
                                              id: "switch-color-error",
                                              color: "error",
                                              defaultChecked: true
                                            }),
                                        label: "Error Color"
                                      })
                                ]
                              }))
                    })
              ]
            });
}

var make = ExampleSwitch;

export {
  make ,
}
/* react Not a pure module */
