// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Core from "@material-ui/core";

function ExampleTabs(Props) {
  var match = React.useReducer((function (param, v) {
          return v;
        }), 2);
  var setValue = match[1];
  var handleChange = function (param, newValue) {
    return Curry._1(setValue, newValue);
  };
  return React.createElement(Core.Paper, {
              children: React.createElement(Core.Tabs, {
                    children: null,
                    indicatorColor: "primary",
                    onChange: handleChange,
                    textColor: "primary",
                    value: match[0]
                  }, React.createElement(Core.Tab, {
                        label: "Active"
                      }), React.createElement(Core.Tab, {
                        disabled: true,
                        label: "Disabled"
                      }), React.createElement(Core.Tab, {
                        label: "Active"
                      })),
              square: true
            });
}

var make = ExampleTabs;

export {
  make ,
  
}
/* react Not a pure module */
