// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Material from "@mui/material";
import * as JsxRuntime from "react/jsx-runtime";
import Menu from "@mui/icons-material/Menu";
import ChevronLeft from "@mui/icons-material/ChevronLeft";
import Notifications from "@mui/icons-material/Notifications";

function px_of_int(x) {
  return String(x) + "px";
}

var MenuIcon = {};

var NotificationsIcon = {};

var ChevronLeftIcon = {};

function ExampleDashboard(props) {
  var match = React.useReducer((function (param, action) {
          if (action === "Open") {
            return {
                    isOpen: true
                  };
          } else {
            return {
                    isOpen: false
                  };
          }
        }), {
        isOpen: true
      });
  var setState = match[1];
  var state = match[0];
  var match$1 = React.useReducer((function (param, v) {
          return v;
        }), false);
  var setShow = match$1[1];
  return JsxRuntime.jsx("div", {
              children: match$1[0] ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx((function (prim) {
                                return Material.CssBaseline(prim);
                              }), {}),
                        JsxRuntime.jsx(Material.AppBar, {
                              children: Caml_option.some(JsxRuntime.jsxs((function (prim) {
                                          return Material.Toolbar(prim);
                                        }), {
                                        children: [
                                          JsxRuntime.jsx((function (prim) {
                                                  return Material.IconButton(prim);
                                                }), {
                                                children: Caml_option.some(JsxRuntime.jsx(Menu, {})),
                                                onClick: (function (_event) {
                                                    setState("Open");
                                                  }),
                                                color: "inherit"
                                              }),
                                          JsxRuntime.jsx((function (prim) {
                                                  return Material.Typography(prim);
                                                }), {
                                                noWrap: true,
                                                variant: "h6",
                                                component: "h1",
                                                children: "Dashboard"
                                              }),
                                          JsxRuntime.jsx((function (prim) {
                                                  return Material.Link(prim);
                                                }), {
                                                color: "text.secondary",
                                                children: "Close Dashboard",
                                                href: "#",
                                                onClick: (function (e) {
                                                    e.preventDefault();
                                                    setShow(false);
                                                  })
                                              }),
                                          JsxRuntime.jsx((function (prim) {
                                                  return Material.IconButton(prim);
                                                }), {
                                                children: Caml_option.some(JsxRuntime.jsx((function (prim) {
                                                            return Material.Badge(prim);
                                                          }), {
                                                          badgeContent: "4",
                                                          children: Caml_option.some(JsxRuntime.jsx(Notifications, {})),
                                                          color: "secondary"
                                                        })),
                                                color: "inherit"
                                              })
                                        ],
                                        disableGutters: !state.isOpen
                                      })),
                              position: "absolute"
                            }),
                        JsxRuntime.jsxs((function (prim) {
                                return Material.Drawer(prim);
                              }), {
                              children: [
                                JsxRuntime.jsx((function (prim) {
                                        return Material.IconButton(prim);
                                      }), {
                                      children: Caml_option.some(JsxRuntime.jsx(ChevronLeft, {})),
                                      onClick: (function (_event) {
                                          setState("Close");
                                        })
                                    }),
                                JsxRuntime.jsx((function (prim) {
                                        return Material.Divider(prim);
                                      }), {}),
                                JsxRuntime.jsx("div", {
                                      children: props.sidebar
                                    })
                              ],
                              open: state.isOpen,
                              variant: "permanent"
                            }),
                        JsxRuntime.jsx("main", {
                              children: JsxRuntime.jsx("div", {
                                    children: props.children
                                  })
                            })
                      ]
                    }) : JsxRuntime.jsx((function (prim) {
                        return Material.Button(prim);
                      }), {
                      children: "Open Dashboard",
                      onClick: (function (param) {
                          setShow(true);
                        }),
                      color: "primary",
                      variant: "outlined"
                    })
            });
}

var drawerWidth = 240;

var make = ExampleDashboard;

export {
  drawerWidth ,
  px_of_int ,
  MenuIcon ,
  NotificationsIcon ,
  ChevronLeftIcon ,
  make ,
}
/* react Not a pure module */
