// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ExampleBox from "./ExampleBox.bs.js";
import * as Server from "react-dom/server";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";
import * as Styles$1 from "@material-ui/core/styles";

var useStyles = Styles.makeStyles({
      code: {
        fontFamily: "SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace",
        marginTop: "15px"
      }
    });

function ExampleServerStyleSheets(Props) {
  var classes = useStyles();
  var match = React.useMemo((function () {
          var sheets = new Styles$1.ServerStyleSheets();
          var html = Server.renderToString(sheets.collect(React.createElement(ExampleBox.make, {})));
          var css = sheets.toString();
          return [
                  html,
                  css
                ];
        }), []);
  return React.createElement("div", undefined, React.createElement(Core.Typography, {
                  children: "ServerSide render of <ExampleBox />",
                  variant: "h5"
                }), React.createElement(Core.TextField, {
                  className: classes.code,
                  defaultValue: match[0],
                  fullWidth: true,
                  label: "HTML",
                  multiline: true,
                  rows: 5,
                  variant: "outlined"
                }), React.createElement(Core.TextField, {
                  className: classes.code,
                  defaultValue: match[1],
                  fullWidth: true,
                  label: "CSS",
                  multiline: true,
                  rows: 5,
                  variant: "outlined"
                }));
}

var make = ExampleServerStyleSheets;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
